//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.chuangmeng.fashiondiy;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import com.chuangmeng.fashiondiy.R.id;
import com.chuangmeng.fashiondiy.R.layout;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HomeActivity_
    extends HomeActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_home);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HomeActivity_.IntentBuilder_ intent(Context context) {
        return new HomeActivity_.IntentBuilder_(context);
    }

    public static HomeActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new HomeActivity_.IntentBuilder_(fragment);
    }

    public static HomeActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new HomeActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        view_home_about_us_iv = ((ImageView) hasViews.findViewById(id.view_home_about_us_iv));
        view_home_all_diy_iv = ((ImageView) hasViews.findViewById(id.view_home_all_diy_iv));
        view_home_female_iv = ((ImageView) hasViews.findViewById(id.view_home_female_iv));
        view_home_male_iv = ((ImageView) hasViews.findViewById(id.view_home_male_iv));
        view_home_couple_iv = ((ImageView) hasViews.findViewById(id.view_home_couple_iv));
        view_home_help_iv = ((ImageView) hasViews.findViewById(id.view_home_help_iv));
        view_home_clothespress_iv = ((ImageView) hasViews.findViewById(id.view_home_clothespress_iv));
        {
            View view = hasViews.findViewById(id.view_home_couple_iv);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HomeActivity_.this.view_home_couple_iv();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_home_female_iv);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HomeActivity_.this.view_home_female_iv();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_home_about_us_iv);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HomeActivity_.this.view_home_about_us_iv();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_home_male_iv);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HomeActivity_.this.view_home_male_iv();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_home_help_iv);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HomeActivity_.this.view_home_help_iv();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.view_home_clothespress_iv);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HomeActivity_.this.view_home_clothespress_iv();
                    }

                }
                );
            }
        }
        initView();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, HomeActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, HomeActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, HomeActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public HomeActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
